tasks:
  - name: Moodle Docker

    before: |
      # Set up Moodle docker environment vars.
      export COMPOSE_PROJECT_NAME=moodle-gitpod
      export MOODLE_DOCKER_WWWROOT="$GITPOD_REPO_ROOT"/moodle
      export MOODLE_DOCKER_DB=pgsql

    init: |
      # Set up Moodle repository.
      .gitpod/setup-env.sh

      # Ensure customized config.php for the Docker containers is in place
      cp config.docker-template.php $MOODLE_DOCKER_WWWROOT/config.php

      # Start up containers.
      bin/moodle-docker-compose up -d

      # Wait for DB to come up.
      bin/moodle-docker-wait-for-db

      # Initialize Moodle database for manual testing.
      bin/moodle-docker-compose exec webserver php admin/cli/install_database.php --agree-license --fullname="Docker moodle" --shortname="docker_moodle" --summary="Docker moodle site" --adminpass="test" --adminemail="admin@example.com"

      # Hack to avoid when the workspace is restarted.
      # It can be removed when https://github.com/gitpod-io/gitpod/issues/17551 is fixed.
      docker exec -it moodle-gitpod-webserver-1 bash -c 'rm -rf /var/log/apache2/*'

      # Open Moodle site in browser.
      gp ports await 8000 && gp preview $(gp url 8000)

      # Initialise behat to add some data.
      wget -O moodle/admin/tool/behat/tests/fixtures/core/basicdata.feature https://gist.githubusercontent.com/sarjona/8f96ca6ac172bfe0ca210b9e831f2544/raw/basicdata.feature
      cd moodle
      git fetch https://github.com/sarjona/moodle/ MDL-behatmacro-master
      git checkout FETCH_HEAD
      cd ..
      bin/moodle-docker-compose exec webserver php admin/tool/behat/cli/init.php
      bin/moodle-docker-compose exec webserver php admin/tool/behat/cli/testscenario.php --feature=./../tests/fixtures/core/basicdata.feature
      cd moodle
      git checkout -
      cd ..

    command: |
      # Update the patch to the latest version.
      cd moodle
      git fetch
      git reset --hard
      cd ..

      # Start up containers.
      bin/moodle-docker-compose up -d

      # Wait for DB to come up.
      bin/moodle-docker-wait-for-db

ports:
  - port: 8000
    name: Moodle server
    visibility: public
    onOpen: ignore
